// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rstkizfcmlxluvbndrju.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJzdGtpemZjbWx4bHV2Ym5kcmp1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE3NjAwMTUsImV4cCI6MjA3NzMzNjAxNX0.TjdIcrPIYmOgjHRBNzHcRsys7kbP6CUtafuuGJKlFZo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});